apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: my-postgres
  namespace: postgres
spec:
  instances:
    - name: instance1
      replicas: 1
      dataVolumeClaimSpec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  backups:
    pgbackrest:
      repos:
        - name: repo1
          volume:
            volumeClaimSpec:
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 1Gi
  users:
    - name: appuser
      options: ["CREATEDB"]
      databases: ["appdb"]
  patroni:
    dynamicConfiguration:
      postgresql:
        parameters:
          max_connections: "100"
  postgresVersion: 15
  storage:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  monitoring:
    pgmonitor:
      exporter: true
---
# PVC (Optional - managed by PostgresCluster usually)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-postgres-pvc
  namespace: postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
# Service to expose PostgreSQL
apiVersion: v1
kind: Service
metadata:
  name: my-postgres-service
  namespace: postgres
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgres
  selector:
    postgres-operator.crunchydata.com/cluster: my-postgres
    role: primary
