apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: duckdns-letsencrypt-staging
spec:
  acme:
    email: armin.grobbelaar256@gmail.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: duckdns-letsencrypt-staging-key
    solvers:
    - dns01:
        webhook:
          groupName: acme.grobbelaar.duckdns.org
          solverName: duckdns
          config:
            tokenSecretRef:
              name: duckdns-token
              key: token
